version: '3'
services:
  analyzer-backend-api-app:
    image: manalyzer/analyzer-backend-api-app:latest
    ports:
      - 8080:8080
  frontend:
    image: geekteam/frontend
    ports:
      - 80:80
    depends_on:
      - analyzer-backend-api-app
