version: '3'
services:
  analyzer-backend-api-app:
    image: manalyzer/analyzer-backend-api-app:latest
    ports:
      - 8080:8080

  frontend:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - /opt/learning/nginx/shared:/var/opt/learning
      - ./front/nginx.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - analyzer-backend-api-app