FROM openjdk:11-oraclelinux8

ARG JAR_FILE

RUN microdnf install nc && microdnf clean all

RUN mkdir -p /apps
COPY ./target/${JAR_FILE} /apps/app.jar
COPY ./entrypoint.sh /apps/entrypoint.sh
COPY ./wait-service.sh /apps/wait-service.sh
RUN chmod +x /apps/entrypoint.sh
RUN chmod +x /apps/wait-service.sh

CMD ["/apps/entrypoint.sh"]